level_0 = {
		'terreno': './niveis/fase1/fase01_terreno.csv',
		'moedas_ouro':'./niveis/fase1/fase01_ouro.csv',
		'moedas_prata':'./niveis/fase1/fase01_prata.csv',
		'moedas_esmeralda':'./niveis/fase1/fase01_esmeralda.csv',
		'grama':'./niveis/fase1/fase01_grama.csv',
		'inimigos':'./niveis/fase1/fase01_inimigos.csv',
		'inimigos3':'./niveis/fase2/mapa2_inimigo.csv',
		'rect': './niveis/fase1/fase01_rect.csv',
		'objetos': './niveis/fase1/fase01_objetos.csv',
		'samurai1': './niveis/fase6/mapa6_samurai1.csv',
		'samurai2': './niveis/fase6/mapa6_samurai2.csv',
		'player': './niveis/fase1/fase01_player.csv',
		'node_pos': (110,400),
		'unlock': 1,
		'node_graphics': './overworld/0'}

level_1 = {
		'terreno': './niveis/fase2/mapa2_terreno.csv',
		'moedas_ouro':'./niveis/fase2/mapa2_ouro.csv',
		'moedas_prata':'./niveis/fase2/mapa2_prata.csv',
		'moedas_esmeralda':'./niveis/fase2/mapa2_esmeralda.csv',
		'grama':'./niveis/fase2/mapa2_grama.csv',
		'inimigos':'./niveis/fase2/mapa2_inimigo.csv',
		'inimigos3':'./niveis/fase2/mapa2_inimigo3.csv',
		'rect': './niveis/fase2/mapa2_rect.csv',
		'samurai1': './niveis/fase6/mapa6_samurai1.csv',
		'samurai2': './niveis/fase6/mapa6_samurai2.csv',
		'objetos': './niveis/fase2/mapa2_objetos.csv',
		'player': './niveis/fase2/mapa2_player.csv',
		'node_pos':(350,220),
		'unlock': 2,
		'node_graphics': './overworld/1'}

level_2 = {
		'terreno': './niveis/fase3/_terreno.csv',
		'moedas_ouro':'./niveis/fase3/_ouro.csv',
		'moedas_prata':'./niveis/fase3/_prata.csv',
		'moedas_esmeralda':'./niveis/fase3/_esmeralda.csv',
		'grama':'./niveis/fase3/_grama.csv',
		'inimigos':'./niveis/fase3/_inimigo.csv',
		'inimigos3':'./niveis/fase2/mapa2_inimigo.csv',
		'rect': './niveis/fase3/_rect.csv',
		'objetos': './niveis/fase3/_objetos.csv',
		'player': './niveis/fase3/_player.csv',
		'samurai1': './niveis/fase6/mapa6_samurai1.csv',
		'samurai2': './niveis/fase6/mapa6_samurai2.csv',
		'node_pos':(470,510),
		'unlock': 3,
		'node_graphics': './overworld/2'}

level_3 = {
		'terreno': './niveis/fase4/mapa4_terreno.csv',
		'moedas_ouro':'./niveis/fase4/mapa4_ouro.csv',
		'moedas_prata':'./niveis/fase4/mapa4_prata.csv',
		'moedas_esmeralda':'./niveis/fase4/mapa4_esmeralda.csv',
		'grama':'./niveis/fase4/mapa4_grama.csv',
		'inimigos':'./niveis/fase2/mapa2_inimigo.csv',
		'inimigos3':'./niveis/fase4/mapa4_inimigo3.csv',
		'rect': './niveis/fase4/mapa4_rect.csv',
		'objetos': './niveis/fase4/mapa4_objeto.csv',
		'player': './niveis/fase4/mapa4_player.csv',
		'samurai1': './niveis/fase6/mapa6_samurai1.csv',
		'samurai2': './niveis/fase6/mapa6_samurai2.csv',
		'node_pos':(710,350),
		'unlock':4,
		'node_graphics': './overworld/3'}

level_4 = {
		'terreno': './niveis/fase5/mapa5_terreno.csv',
		'moedas_ouro':'./niveis/fase5/mapa5_ouro.csv',
		'moedas_prata':'./niveis/fase5/mapa5_prata.csv',
		'moedas_esmeralda':'./niveis/fase5/mapa5_esmeralda.csv',
		'grama':'./niveis/fase5/mapa5_grama.csv',
		'inimigos':'./niveis/fase5/mapa5_inimigo.csv',
		'inimigos3':'./niveis/fase2/mapa2_inimigo.csv',
		'rect': './niveis/fase5/mapa5_rect.csv',
		'objetos': './niveis/fase5/mapa5_objeto.csv',
		'player': './niveis/fase5/mapa5_player.csv',
		'samurai1': './niveis/fase6/mapa6_samurai1.csv',
		'samurai2': './niveis/fase6/mapa6_samurai2.csv',
		'node_pos':(940,210),
		'unlock':5,
		'node_graphics': './overworld/4'}

level_5 = {
		'terreno': './niveis/fase6/mapa6_terreno.csv',
		'moedas_ouro':'./niveis/fase6/mapa6_ouro.csv',
		'moedas_prata':'./niveis/fase6/mapa6_prata.csv',
		'moedas_esmeralda':'./niveis/fase6/mapa6_esmeralda.csv',
		'grama':'./niveis/fase6/mapa6_grama.csv',
		'inimigos':'./niveis/fase6/mapa6_inimigo.csv',
		'inimigos3':'./niveis/fase2/mapa2_inimigo.csv',
		'rect': './niveis/fase6/mapa6_rect.csv',
		'objetos': './niveis/fase6/mapa6_objetos.csv',
		'player': './niveis/fase6/mapa6_player.csv',
		'samurai1': './niveis/fase6/mapa6_samurai1.csv',
		'samurai2': './niveis/fase6/mapa6_samurai2.csv',
		'node_pos':(1150,400),
		'unlock':5,
		'node_graphics': './overworld/5'}

levels = {
	0: level_0,
	1: level_1,
	2: level_2,
	3: level_3,
	4: level_4,
	5: level_5}